/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Profesor;
import Logic.Crud;
import static Logic.Crud.guardarBloques;
import static Logic.Crud.guardarProfesores;
import static Logic.Crud.guardarUsuarios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ruben Dario Guarnizo
 */
public class RegistroProfesor extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public RegistroProfesor() {
        initComponents();
        this.setLocationRelativeTo(null);
        botonesTransparentes();
        this.remove(btnCambiarHorario);
    }
    public RegistroProfesor(boolean esProfesor)
    {
        initComponents();
        this.setLocationRelativeTo(null);
        botonesTransparentes();
        deshabilitarCampos();
        this.remove(btnSerProfesor);
    }

    private void botonesTransparentes() {

        btnSerProfesor.setOpaque(false);
        btnSerProfesor.setContentAreaFilled(false);
        btnSerProfesor.setBorderPainted(false);
        
        btnCambiarHorario.setOpaque(false);
        btnCambiarHorario.setContentAreaFilled(false);
        btnCambiarHorario.setBorderPainted(false);

        btn2.setOpaque(false);
        btn2.setContentAreaFilled(false);
        btn2.setBorderPainted(false);

        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);

    }

    private boolean camposVacios() {
        if (txtCobro.getText().isEmpty() || txtContrasena.getText().isEmpty() || txtCorreo.getText().isEmpty()) {
            return true;
        } else {
            return false;
        }
    }
    private void deshabilitarCampos()
    {
        cbxMateria.setEnabled(false);
        txtCobro.setEnabled(false);
        txtContrasena.setEnabled(false);
        txtCorreo.setEnabled(false);
        btnSerProfesor.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSerProfesor = new javax.swing.JButton();
        btnCambiarHorario = new javax.swing.JButton();
        txtCobro = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btn2 = new javax.swing.JButton();
        cbxMateria = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHorario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSerProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSerProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSerProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 160, 60));

        btnCambiarHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 160, 60));
        getContentPane().add(txtCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 70, 30));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 190, 30));
        getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 190, 30));

        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 50, 60));

        cbxMateria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ciencias exactas", "Ciencias medicas", "Ciencias humanas", "Ciencias naturales" }));
        getContentPane().add(cbxMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 30));

        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 60, 50));

        tblHorario.setForeground(new java.awt.Color(49, 50, 51));
        tblHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"9:00 -10:00", null, null, null, null, null},
                {"10:00 -11:00", null, null, null, null, null},
                {"11:00-12:00", null, null, null, null, null},
                {"14:00-15:00", null, null, null, null, null},
                {"15:00-16:00", null, null, null, null, null},
                {"16:00-17:00", null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHorario.setColumnSelectionAllowed(true);
        tblHorario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblHorario.getTableHeader().setReorderingAllowed(false);
        tblHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHorarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHorario);
        tblHorario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblHorario.getColumnModel().getColumnCount() > 0) {
            tblHorario.getColumnModel().getColumn(0).setMinWidth(75);
            tblHorario.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblHorario.getColumnModel().getColumn(0).setMaxWidth(85);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 360, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI Recursos/Registro-Profesor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSerProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerProfesorActionPerformed

        if (camposVacios()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese todos los datos por favor", "Campos vacios", JOptionPane.WARNING_MESSAGE);
        } else {
            if (Logic.Login.verificarSesion(txtCorreo.getText(), txtContrasena.getText())==false) {
                JOptionPane.showMessageDialog(rootPane, "Verifique sus datos de usuario", "Error de usuario", JOptionPane.ERROR_MESSAGE);
            } else {
                String areaADictar = cbxMateria.getSelectedItem().toString();
                double cobroPorHora = Double.parseDouble(txtCobro.getText());
                String correo = txtCorreo.getText();
                String contraseña = txtContrasena.getText();
                Logic.Crud.registrarProfesor(areaADictar, cobroPorHora, correo, contraseña, tblHorario.getModel());
                JOptionPane.showMessageDialog(rootPane, "Ahora eres profesor", "Exito", JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnSerProfesorActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        new SerProfesor().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      System.out.println("Guardando Usuarios...");
        guardarUsuarios();
        System.out.println("Los Usuarios se han guardado con exito ");
        System.out.println("Guardando Profesores...");
        guardarProfesores();
        System.out.println("Los Profesores se han guardado con exito");
        System.out.println("Guardando Blockchain...");
        guardarBloques();
        System.out.println("BlockchainGuardado Exitosamente");
       
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHorarioMouseClicked
        //Obtener la fila
        int fila = tblHorario.rowAtPoint(evt.getPoint());
        int columna = tblHorario.columnAtPoint(evt.getPoint());
        
        if (!(tblHorario.getValueAt(fila, columna)==null)) {
            tblHorario.setValueAt(null, fila, columna);
        } else {
            switch (fila) {
                case 0:
                    tblHorario.setValueAt(9, fila, columna);
                    break;
                case 1:
                    tblHorario.setValueAt(10, fila, columna);
                    break;
                case 2:
                    tblHorario.setValueAt(11, fila, columna);
                    break;
                case 3:
                    tblHorario.setValueAt(14, fila, columna);
                    break;
                case 4:
                    tblHorario.setValueAt(15, fila, columna);
                    break;
                case 5:
                    tblHorario.setValueAt(16, fila, columna);
                    break;

            }

        }

    }//GEN-LAST:event_tblHorarioMouseClicked

    private void btnCambiarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarHorarioActionPerformed

        TableModel horario = this.tblHorario.getModel();
        for(Profesor profesor: Crud.listaProfesores)
        {
            if(profesor.getCorreo().equals(Login.correo))
            {
                profesor.setHorario(tblHorario.getModel());
                
            }
        }

        JOptionPane.showMessageDialog(rootPane, "El horario ha sido actualizado con exito", "Exito!", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnCambiarHorarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroProfesor().setVisible(true);
            }
        });
    }

    private void establecerHorario(int fila) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnCambiarHorario;
    private javax.swing.JButton btnSerProfesor;
    private javax.swing.JComboBox cbxMateria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHorario;
    private javax.swing.JTextField txtCobro;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
