/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Clase;
import Data.Profesor;
import static Logic.Crud.guardarBloques;
import static Logic.Crud.guardarProfesores;
import static Logic.Crud.guardarUsuarios;
import static Logic.Crud.listaProfesores;
import static Logic.Crud.verificarEsProfesor;
import static Logic.Login.listaUsuarios;
import static UI.Login.correo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruben Dario Guarnizo
 */
public class VerTutoria extends javax.swing.JFrame {

    public ArrayList<Clase> listaClases = new ArrayList<>();
    /**
     * Creates new form SerProfesor
     */
    public VerTutoria() {
        initComponents();
        this.setLocationRelativeTo(null);
        botonesTransparentes();
        definirTablaClases();
    }

    private void definirTablaClases() {

        ArrayList<Clase> listaClases = null;
        String dia="";
        for (Profesor profe : listaProfesores) {
            if (profe.getUsuario().getCorreo().equals(correo)) {
                listaClases = profe.getListaClases();
            }
        }

        if (verificarEsProfesor() == false) {
            System.out.println("No eres profesor aun!");
        } else {

            DefaultTableModel modelo = new DefaultTableModel();

            modelo.addColumn("Nombre Alumno");
            modelo.addColumn("Lugar/Sitio");
            modelo.addColumn("Hora/Fecha");
            for (Clase clas : listaClases) {
                
                switch (clas.getFecha().getDay()) {
                    case 1:
                        dia = "Lunes";
                        break;
                    case 2:
                        dia = "Martes";
                        break;
                    case 3:
                        dia = "Miercoles";
                        break;
                    case 4:
                        dia = "Jueves";
                        break;
                    case 5:
                        dia = "Viernes ";
                        break;
                }
                String[] fila = {clas.getEstudianteQueRecibe().getNombre(), clas.getLugar(), Long.toString(clas.getFecha().getHours()) + ":00" + ',' + dia };
                modelo.addRow(fila);
            }
            tblTutorias.setModel(modelo);
        }
    }

    public void botonesTransparentes() {

        btnCancelarTutoria.setOpaque(false);
        btnCancelarTutoria.setContentAreaFilled(false);
        btnCancelarTutoria.setBorderPainted(false);

        btn2.setOpaque(false);
        btn2.setContentAreaFilled(false);
        btn2.setBorderPainted(false);

        btn3.setOpaque(false);
        btn3.setContentAreaFilled(false);
        btn3.setBorderPainted(false);

        btn4.setOpaque(false);
        btn4.setContentAreaFilled(false);
        btn4.setBorderPainted(false);

        btn5.setOpaque(false);
        btn5.setContentAreaFilled(false);
        btn5.setBorderPainted(false);

        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);

        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelarTutoria = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTutorias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelarTutoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarTutoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTutoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarTutoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 200, 50));

        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, 50));

        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 200, 50));

        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 50));

        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 200, 50));

        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 495, 50, 40));

        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 10, 60, 60));

        tblTutorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Lugar", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTutorias.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblTutorias);
        tblTutorias.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 480, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI Recursos/Ver_Tutorias.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarTutoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTutoriaActionPerformed
        int fila = tblTutorias.getSelectedRow();
        int columna = tblTutorias.getSelectedColumn();
        int posicionAEliminar1 = -1;
        int posicionAEliminar2 = -1;
        String estudianteAEliminar="";
        ArrayList<Clase> listaClasesEliminar= new ArrayList<>();
        int respuesta = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que desea eliminar?", "Verificacion eliminar", JOptionPane.YES_NO_CANCEL_OPTION);
        
        for(int i=0; i<Logic.Crud.listaProfesores.size();i++)
        {
            if(listaProfesores.get(i).getCorreo().equals(Logic.Login.usuarioLogeado))
            {
                listaClases= listaProfesores.get(i).getListaClases();
            }
        }
                  
        
        if (respuesta == 0) {
            if (columna == 0) {
                for (int i = 0; i < listaClases.size(); i++) {
                    if (listaClases.get(i).getEstudianteQueRecibe().getNombre().equals(tblTutorias.getValueAt(fila, columna))) {
                        posicionAEliminar1 = i;
                        estudianteAEliminar= listaClases.get(i).getEstudianteQueRecibe().getCorreo();
                    }
                }
                listaClasesEliminar= listaUsuarios.get(estudianteAEliminar).getListaClases();
                listaClases.remove(posicionAEliminar1);
                
                for(int i=0; i<listaClasesEliminar.size();i++)
                {
                    if(listaClasesEliminar.get(i).getEstudianteQueRecibe().getNombre().equals(tblTutorias.getValueAt(fila, columna)))
                    {
                        posicionAEliminar2=i;
                    }
                }
                listaClasesEliminar.remove(posicionAEliminar2);
                definirTablaClases();
                JOptionPane.showMessageDialog(rootPane, "Clase eliminada con exito", "Exito", JOptionPane.INFORMATION_MESSAGE);
                new MenuPrincipal().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Para eliminar seleccione el nombre del profesor de la clase", "Seleccion invalida", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCancelarTutoriaActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:

        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("Guardando Usuarios...");
        guardarUsuarios();
        System.out.println("Los Usuarios se han guardado con exito ");
        System.out.println("Guardando Profesores...");
        guardarProfesores();
        System.out.println("Los Profesores se han guardado con exito");
        System.out.println("Guardando Blockchain...");
        guardarBloques();
        System.out.println("BlockchainGuardado Exitosamente");

        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
         if ("Nimbus".equals(info.getName())) {
         javax.swing.UIManager.setLookAndFeel(info.getClassName());
         break;
         }
         }
         } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(VerTutoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(VerTutoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(VerTutoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(VerTutoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
         //</editor-fold>
         //</editor-fold>
         //</editor-fold>
         //</editor-fold>

         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerTutoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btnCancelarTutoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTutorias;
    // End of variables declaration//GEN-END:variables
}
